# Generated by Django 5.2.17 on 2026-09-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='logo',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='logo_bg',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=5),
        ),
        migrations.AddField(
            model_name='location',
            name='logo_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='location',
            name='logo_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
